export const CARD_TYPES: string[] = [
        'Attack',
        'Attack Reaction',
        'Action',
        'Defense',
        'Defense Reaction',
        'Equipment',
        'Equipment - Arms',
        'Equipment - Chest',
        'Equipment - Head',
        'Equipment - Legs',
        'Hero',
        'Hero - Adult',
        'Hero - Young',
        'Instant',
        'Token',
        'Weapon - 1H',
        'Weapon - 2H',
];

